// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCrudAsp.Data;

#nullable disable

namespace SimpleCrudAsp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230804204018_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");
#pragma warning restore 612, 618
        }
    }
}
